export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";

export const UPDATE_SUBSCRIPTIONS = "UPDATE_SUBSCRIPTIONS";
export const UPDATE_SUBSCRIPTIONS_FAIL = "UPDATE_SUBSCRIPTIONS_FAIL";
export const CLEAR_SUBSCRIPTIONS = "CLEAR_SUBSCRIPTIONS";
